// mdClientState.cc - xmlrpc-c C++ proxy class
// Auto-generated by xml-rpc-api2cpp.

#include <xmlrpc-c/oldcppwrapper.hpp>
#include "mdClientState.h"

XmlRpcValue::int32 mdClientState::getMDversion (std::string const string1) {
    XmlRpcValue params(XmlRpcValue::makeArray());
    params.arrayAppendItem(XmlRpcValue::makeString(string1));
    XmlRpcValue result(this->mClient.call("state.getMDversion", params));
    return result.getInt();
}

std::string mdClientState::create (XmlRpcValue::int32 const int1, std::string const string2, std::string const string3) {
    XmlRpcValue params(XmlRpcValue::makeArray());
    params.arrayAppendItem(XmlRpcValue::makeInt(int1));
    params.arrayAppendItem(XmlRpcValue::makeString(string2));
    params.arrayAppendItem(XmlRpcValue::makeString(string3));
    XmlRpcValue result(this->mClient.call("state.create", params));
    return result.getString();
}

XmlRpcValue /*struct*/ mdClientState::get (XmlRpcValue::int32 const int1, std::string const string2) {
    XmlRpcValue params(XmlRpcValue::makeArray());
    params.arrayAppendItem(XmlRpcValue::makeInt(int1));
    params.arrayAppendItem(XmlRpcValue::makeString(string2));
    XmlRpcValue result(this->mClient.call("state.get", params));
    return result;
}

std::string mdClientState::set (XmlRpcValue::int32 const int1, XmlRpcValue /*struct*/ struct2) {
    XmlRpcValue params(XmlRpcValue::makeArray());
    params.arrayAppendItem(XmlRpcValue::makeInt(int1));
    params.arrayAppendItem(struct2);
    XmlRpcValue result(this->mClient.call("state.set", params));
    return result.getString();
}
