// mdClientDevice.cc - xmlrpc-c C++ proxy class
// Auto-generated by xml-rpc-api2cpp.

#include <xmlrpc-c/oldcppwrapper.hpp>
#include "mdClientDevice.h"

XmlRpcValue::int32 mdClientDevice::registeR (XmlRpcValue::int32 const int1, std::string const string2) {
    XmlRpcValue params(XmlRpcValue::makeArray());
    params.arrayAppendItem(XmlRpcValue::makeInt(int1));
    params.arrayAppendItem(XmlRpcValue::makeString(string2));
    XmlRpcValue result(this->mClient.call("device.registeR", params));
    return result.getInt();
}
